import type { Metadata } from "next";
import { Inter, Inter_Tight } from "next/font/google";
import { twMerge } from "tailwind-merge";
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "./globals.css";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Inter_Tight({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevLinks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={twMerge(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          "h-dvh w-dvw",
          "bg-[url(/light-bg-mobile.png)] lg:bg-[url(/light-bg-desktop.png)] bg-cover bg-center bg-no-repeat",
          "dark:bg-[url(/dark-bg-mobile.png)] dark:lg:bg-[url(/dark-bg-desktop.png)]"
        )}
      >
        <NextIntlClientProvider>
          <ThemeProvider enableSystem defaultTheme="system">
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
